// <auto-generated />
using System;
using Cicci.SampleManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Sample_Manager_Tool.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20260908122357_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Cicci.SampleManager.Models.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float?>("Area")
                        .HasColumnType("REAL");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceStackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DeviceStackId");

                    b.HasIndex("UserId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pixel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SampleId", "Pixel")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.DeviceStack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeviceStacks");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.ResearchUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ResearchUsers");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "Code")
                        .IsUnique();

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.StackLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceStackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceStackId", "Position")
                        .IsUnique();

                    b.ToTable("StackLayers");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Batch", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.DeviceStack", "DeviceStack")
                        .WithMany("Batches")
                        .HasForeignKey("DeviceStackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cicci.SampleManager.Models.ResearchUser", "User")
                        .WithMany("Batches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceStack");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Device", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.Sample", "Sample")
                        .WithMany("Devices")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Sample", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.Batch", "Batch")
                        .WithMany("Samples")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.StackLayer", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.DeviceStack", "DeviceStack")
                        .WithMany("Layers")
                        .HasForeignKey("DeviceStackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceStack");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Batch", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.DeviceStack", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Layers");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.ResearchUser", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Sample", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
