// <auto-generated />
using System;
using Cicci.SampleManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Sample_Manager_Tool.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20260925092418_FixMeasurementArtifacts")]
    partial class FixMeasurementArtifacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Cicci.SampleManager.Models.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float?>("Area")
                        .HasColumnType("REAL");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceStackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DeviceStackId");

                    b.HasIndex("UserId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.DarkJvMeasurement", b =>
                {
                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PeakElEqePercent")
                        .HasColumnType("REAL");

                    b.HasKey("MeasurementId");

                    b.ToTable("DarkJvMeasurements");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pixel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SampleId", "Pixel")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.DeviceStack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeviceStacks");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.EisMeasurement", b =>
                {
                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PeakFrequencyHz")
                        .HasColumnType("REAL");

                    b.HasKey("MeasurementId");

                    b.ToTable("EisMeasurements");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.EqeMeasurement", b =>
                {
                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Jsc")
                        .HasColumnType("REAL");

                    b.Property<double?>("PeakEQE")
                        .HasColumnType("REAL");

                    b.HasKey("MeasurementId");

                    b.ToTable("EqeMeasurements");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.JvMeasurement", b =>
                {
                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EfficiencyPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("FillFactorPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("JmppMilliampPerCm2")
                        .HasColumnType("REAL");

                    b.Property<double?>("JscMilliampPerCm2")
                        .HasColumnType("REAL");

                    b.Property<double?>("PmppMilliwattPerCm2")
                        .HasColumnType("REAL");

                    b.Property<double?>("VmppV")
                        .HasColumnType("REAL");

                    b.Property<double?>("VocV")
                        .HasColumnType("REAL");

                    b.HasKey("MeasurementId");

                    b.ToTable("JvMeasurements");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataPath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MeasurementSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Type", "MeasuredAt");

                    b.HasIndex("MeasurementSessionId", "DeviceId", "MeasuredAt");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.MeasurementArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId", "Kind");

                    b.ToTable("MeasurementArtifacts");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.MeasurementSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MeasurementSessions");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.MeasurementSessionDevice", b =>
                {
                    b.Property<Guid>("MeasurementSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.HasKey("MeasurementSessionId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("MeasurementSessionDevices");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.ResearchUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ResearchUsers");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "Code")
                        .IsUnique();

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.StackLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceStackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceStackId", "Position")
                        .IsUnique();

                    b.ToTable("StackLayers");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Batch", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.DeviceStack", "DeviceStack")
                        .WithMany("Batches")
                        .HasForeignKey("DeviceStackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cicci.SampleManager.Models.ResearchUser", "User")
                        .WithMany("Batches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceStack");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.DarkJvMeasurement", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.Measurement", "Measurement")
                        .WithOne("DarkJV")
                        .HasForeignKey("Cicci.SampleManager.Models.DarkJvMeasurement", "MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Device", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.Sample", "Sample")
                        .WithMany("Devices")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.EisMeasurement", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.Measurement", "Measurement")
                        .WithOne("Eis")
                        .HasForeignKey("Cicci.SampleManager.Models.EisMeasurement", "MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.EqeMeasurement", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.Measurement", "Measurement")
                        .WithOne("Eqe")
                        .HasForeignKey("Cicci.SampleManager.Models.EqeMeasurement", "MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.JvMeasurement", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.Measurement", "Measurement")
                        .WithOne("Jv")
                        .HasForeignKey("Cicci.SampleManager.Models.JvMeasurement", "MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Measurement", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.Device", "Device")
                        .WithMany("Measurements")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cicci.SampleManager.Models.MeasurementSession", "MeasurementSession")
                        .WithMany("Measurements")
                        .HasForeignKey("MeasurementSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Device");

                    b.Navigation("MeasurementSession");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.MeasurementArtifact", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.Measurement", "Measurement")
                        .WithMany("Artifacts")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.MeasurementSessionDevice", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.Device", "Device")
                        .WithMany("SessionMemberships")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cicci.SampleManager.Models.MeasurementSession", "MeasurementSession")
                        .WithMany("Participants")
                        .HasForeignKey("MeasurementSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("MeasurementSession");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Sample", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.Batch", "Batch")
                        .WithMany("Samples")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.StackLayer", b =>
                {
                    b.HasOne("Cicci.SampleManager.Models.DeviceStack", "DeviceStack")
                        .WithMany("Layers")
                        .HasForeignKey("DeviceStackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceStack");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Batch", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Device", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("SessionMemberships");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.DeviceStack", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Layers");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Measurement", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("DarkJV");

                    b.Navigation("Eis");

                    b.Navigation("Eqe");

                    b.Navigation("Jv");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.MeasurementSession", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.ResearchUser", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("Cicci.SampleManager.Models.Sample", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
